
{{ if .Values.jmeter.master.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-data-dir-pvc
spec:
  accessModes:
    - {{ .Values.jmeter.master.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.jmeter.master.persistence.capacity }}
{{ end }}