{{ if .Values.influxdb.persistence }}
apiVersion: v1
stringData:
  INFLUXDB_ADMIN_USER: {{ .Values.influxdb.adminUser }}
  INFLUXDB_ADMIN_USER_PASSWORD: {{ .Values.influxdb.adminPassword }}
  INFLUXDB_DB: {{ .Values.influxdb.dbName }}
  INFLUXDB_HOST: {{ .Values.influxdb.host }}
  INFLUXDB_HTTP_AUTH_ENABLED: {{ .Values.influxdb.enableAuth | quote }}
  INFLUXDB_READ_USER: {{ .Values.influxdb.readOnlyUser }}
  INFLUXDB_USER: {{ .Values.influxdb.user }}
  INFLUXDB_USER_PASSWORD: {{ .Values.influxdb.userPassword }}
kind: Secret
metadata:
  name: influxdb-creds
  namespace: {{ .Values.namespace }}
type: Opaque
{{ end }}