{{ if .Values.grafana.enabled }}
{{ if .Values.grafana.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  ports:
  - port: {{ .Values.grafana.service.port }}
    name: https
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
{{ end }}
{{ end }}