{{ if .Values.cleaner.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: my-completed-jobs-cleaner-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
{{ end }}