{{ if .Values.wiremock.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-wiremock
spec:
  maxReplicas: {{ .Values.wiremock.maxReplicas }}
  minReplicas: {{ .Values.wiremock.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wiremock
  targetCPUUtilizationPercentage: {{ .Values.wiremock.targetCpuUsage }}
{{ end }}