{{ if .Values.demo.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-target
spec:
  maxReplicas: {{ .Values.demo.maxReplicas }}
  minReplicas: {{ .Values.demo.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: target
  targetCPUUtilizationPercentage: {{ .Values.demo.targetCpuUsage}}
{{ end }}