apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.jmeter.slave.service.ports.jmeter }}
    name: jmeter
    targetPort: 1099
  - port: {{ .Values.jmeter.slave.service.ports.rmi }}
    name: rmi
    targetPort: 50000
  - port: {{ .Values.jmeter.slave.service.ports.stopTest }}
    name: stoptest
    targetPort: 4445
  selector:
    jmeter_mode: slave